/** Conversation state TTL — abandon a stalled search after this long. */
export const CONVERSATION_TTL_SECONDS = 15 * 60;

export const CONVERSATION_KEY_PREFIX = "flights-bot:conv:";

/** Small, extendable city/airport → IATA lookup for common Israeli-traveler destinations. */
export const CITY_IATA: Record<string, string> = {
  "תל אביב": "TLV",
  "תא": "TLV",
  "tel aviv": "TLV",
  "אילת": "ETM",
  "eilat": "ETM",
  "לונדון": "LON",
  "london": "LON",
  "פריז": "PAR",
  "paris": "PAR",
  "ניו יורק": "NYC",
  "new york": "NYC",
  "ברצלונה": "BCN",
  "barcelona": "BCN",
  "מדריד": "MAD",
  "madrid": "MAD",
  "רומא": "ROM",
  "rome": "ROM",
  "מילאנו": "MIL",
  "milan": "MIL",
  "אתונה": "ATH",
  "athens": "ATH",
  "לרנקה": "LCA",
  "larnaca": "LCA",
  "פאפוס": "PFO",
  "paphos": "PFO",
  "איסטנבול": "IST",
  "istanbul": "IST",
  "בנגקוק": "BKK",
  "bangkok": "BKK",
  "אמסטרדם": "AMS",
  "amsterdam": "AMS",
  "ברלין": "BER",
  "berlin": "BER",
  "מינכן": "MUC",
  "munich": "MUC",
  "ורשה": "WAW",
  "warsaw": "WAW",
  "בודפשט": "BUD",
  "budapest": "BUD",
  "פראג": "PRG",
  "prague": "PRG",
  "וינה": "VIE",
  "vienna": "VIE",
  "ליסבון": "LIS",
  "lisbon": "LIS",
  "דובאי": "DXB",
  "dubai": "DXB",
  "טביליסי": "TBS",
  "tbilisi": "TBS",
  "באטומי": "BUS",
  "batumi": "BUS",
  "זנזיבר": "ZNZ",
  "zanzibar": "ZNZ",
  "בקו": "BAK",
  "baku": "BAK",
};

export function resolveIata(place: string): string | null {
  return CITY_IATA[place.trim().toLowerCase()] ?? null;
}
