/** Hebrew team labels and flag emoji for FIFA national teams. */

export const FIFA_TO_ALPHA2: Record<string, string> = {
  ALG: "DZ",
  ARG: "AR",
  AUS: "AU",
  AUT: "AT",
  BEL: "BE",
  BIH: "BA",
  BRA: "BR",
  CAN: "CA",
  CIV: "CI",
  COD: "CD",
  COL: "CO",
  CPV: "CV",
  CRO: "HR",
  CUW: "CW",
  CZE: "CZ",
  ECU: "EC",
  EGY: "EG",
  ENG: "GB",
  ESP: "ES",
  FRA: "FR",
  GER: "DE",
  GHA: "GH",
  HAI: "HT",
  IRN: "IR",
  IRQ: "IQ",
  JOR: "JO",
  JPN: "JP",
  KOR: "KR",
  KSA: "SA",
  MAR: "MA",
  MEX: "MX",
  NED: "NL",
  NOR: "NO",
  NZL: "NZ",
  PAN: "PA",
  PAR: "PY",
  POR: "PT",
  QAT: "QA",
  RSA: "ZA",
  SCO: "GB",
  SEN: "SN",
  SUI: "CH",
  SWE: "SE",
  TUN: "TN",
  TUR: "TR",
  URU: "UY",
  USA: "US",
  UZB: "UZ",
};

export const HEBREW_TEAM_NAMES: Record<string, string> = {
  ALG: "אלג'יריה",
  ARG: "ארגנטינה",
  AUS: "אוסטרליה",
  AUT: "אוסטריה",
  BEL: "בלגיה",
  BIH: "בוסניה והרצגובינה",
  BRA: "ברזיל",
  CAN: "קנדה",
  CIV: "חוף השנהב",
  COD: "קונגו",
  COL: "קולומביה",
  CPV: "כף הירוקה",
  CRO: "קרואטיה",
  CUW: "קוראסאו",
  CZE: "צ'כיה",
  ECU: "אקואדור",
  EGY: "מצרים",
  ENG: "אנגליה",
  ESP: "ספרד",
  FRA: "צרפת",
  GER: "גרמניה",
  GHA: "גאנה",
  HAI: "האיטי",
  IRN: "איראן",
  IRQ: "עיראק",
  JOR: "ירדן",
  JPN: "יפן",
  KOR: "דרום קוריאה",
  KSA: "ערב הסעודית",
  MAR: "מרוקו",
  MEX: "מקסיקו",
  NED: "הולנד",
  NOR: "נורווגיה",
  NZL: "ניו זילנד",
  PAN: "פנמה",
  PAR: "פרגואי",
  POR: "פורטוגל",
  QAT: "קטר",
  RSA: "דרום אפריקה",
  SCO: "סקוטלנד",
  SEN: "סנגל",
  SUI: "שווייץ",
  SWE: "שבדיה",
  TUN: "תוניסיה",
  TUR: "טורקיה",
  URU: "אורוגוואי",
  USA: 'ארה"ב',
  UZB: "אוזבקיסטן",
};

export function countryFlag(fifaCode: string): string {
  const alpha2 = FIFA_TO_ALPHA2[fifaCode.toUpperCase()];
  if (!alpha2 || alpha2.length !== 2) return "";
  return [...alpha2.toUpperCase()]
    .map((char) => String.fromCodePoint(0x1f1e6 + char.charCodeAt(0) - 65))
    .join("");
}

export function hebrewTeamName(fifaCode: string, englishName: string): string {
  return HEBREW_TEAM_NAMES[fifaCode.toUpperCase()] ?? englishName;
}
