/** TLV — Ben Gurion Airport */
export const FLIGHT_DEALS_ORIGIN = "TLV";

/** Maximum round-trip price in USD. */
export const FLIGHT_DEALS_MAX_PRICE_USD = Number(
  process.env.FLIGHT_DEALS_MAX_PRICE_USD ?? "50",
);

export const FLIGHT_DEALS_CURRENCY = "USD";

/** Cron interval — every 30 minutes. */
export const FLIGHT_DEALS_SCAN_INTERVAL_CRON = "*/30 * * * *";

export const AMADEUS_API_BASE =
  process.env.AMADEUS_API_BASE ?? "https://test.api.amadeus.com";

export const AMADEUS_CLIENT_ID = process.env.AMADEUS_CLIENT_ID ?? "";
export const AMADEUS_CLIENT_SECRET = process.env.AMADEUS_CLIENT_SECRET ?? "";

/** Redis keys for deduplication and history. */
export const FLIGHT_DEALS_SEEN_KEY = "flight-deals:seen";
export const FLIGHT_DEALS_HISTORY_KEY = "flight-deals:history";
export const FLIGHT_DEALS_MAX_HISTORY = 200;

/** Common destination names for Hebrew messages (IATA → label). */
export const AIRPORT_LABELS: Record<string, string> = {
  TLV: "תל אביב",
  ATH: "אתונה",
  LCA: "לרנקה",
  PFO: "פאפוס",
  BUD: "בודפשט",
  BUH: "בוקרשט",
  OTP: "בוקרשט",
  SOF: "סופיה",
  VAR: "ורנה",
  TBS: "טביליסי",
  EVN: "ירוואן",
  DXB: "דובאי",
  AYT: "אנטליה",
  IST: "איסטנבול",
  SAW: "איסטנבול",
  BKK: "בנגקוק",
  FCO: "רומא",
  CIA: "רומא",
  MXP: "מילאנו",
  LIN: "מילאנו",
  BGY: "מילאנו",
  BCN: "ברצלונה",
  MAD: "מדריד",
  LIS: "ליסבון",
  PRG: "פראג",
  VIE: "וינה",
  WAW: "ורשה",
  KRK: "קרקוב",
  RIX: "ריגה",
  TLL: "טאלין",
  CAI: "קהיר",
  AMM: "עמאן",
  RAK: "מרקש",
  RBA: "רבאט",
  CMN: "קזבלנקה",
  VCE: "ונציה",
  NAP: "נאפולי",
  LGW: "לונדון",
  LHR: "לונדון",
  STN: "לונדון",
  LTN: "לונדון",
  BER: "ברלין",
  MUC: "מינכן",
  FRA: "פרנקפורט",
  AMS: "אמסטרדם",
  BRU: "בריסל",
  ZRH: "ציריך",
  GVA: "ז׳נבה",
  NCE: "ניס",
  CDG: "פריז",
  ORY: "פריז",
  DUS: "דיסלדורף",
  STR: "שטוטגרט",
  SKG: "סלוניקי",
  HER: "הרקליון",
  RHO: "רודוס",
  JMK: "מיקונוס",
  JTR: "סנטוריני",
  BUS: "בתומי",
  GYD: "באקו",
  ALA: "אלמטי",
  TSE: "אסטנה",
  KIV: "קישינב",
  BEG: "בלגרד",
  TIA: "טירנה",
  SKP: "סקופיה",
  ZAG: "זגרב",
  LJU: "לובליאנה",
  DBV: "דוברובניק",
  SPU: "ספליט",
  FAO: "פארו",
  AGP: "מלגה",
  ALC: "אליקנטה",
  PMI: "מיורקה",
  IBZ: "איביזה",
  TFS: "טנריף",
  AUH: "אבו דאבי",
  DOH: "דוחה",
  BAH: "מנאמה",
  SEO: "סיאול",
  ICN: "סיאול",
  NRT: "טוקיו",
  HND: "טוקיו",
  DMK: "בנגקוק",
  SIN: "סינגפור",
  HKT: "פוקט",
  MLE: "מאלדיבים",
  CMB: "קולומבו",
  BOM: "מומבאי",
  DEL: "דלהי",
  NYC: "ניו יורק",
  JFK: "ניו יורק",
  EWR: "ניו יורק",
  LAX: "לוס אנג׳לס",
  MIA: "מיאמי",
  YYZ: "טורונטו",
  ETH: "אילת",
  ETM: "אילת",
};

/** IATA → country (Hebrew) for message formatting. */
export const COUNTRY_LABELS: Record<string, string> = {
  ATH: "יוון",
  SKG: "יוון",
  HER: "יוון",
  RHO: "יוון",
  JMK: "יוון",
  JTR: "יוון",
  LCA: "קפריסין",
  PFO: "קפריסין",
  BUD: "הונגריה",
  OTP: "רומניה",
  SOF: "בולגריה",
  VAR: "בולגריה",
  IST: "טורקיה",
  SAW: "טורקיה",
  AYT: "טורקיה",
  DXB: "איחוד האמירויות",
  AUH: "איחוד האמירויות",
  BCN: "ספרד",
  MAD: "ספרד",
  AGP: "ספרד",
  ALC: "ספרד",
  PMI: "ספרד",
  IBZ: "ספרד",
  TFS: "ספרד",
  FCO: "איטליה",
  CIA: "איטליה",
  MXP: "איטליה",
  LIN: "איטליה",
  BGY: "איטליה",
  VCE: "איטליה",
  NAP: "איטליה",
  PRG: "צ׳כיה",
  WAW: "פולין",
  KRK: "פולין",
  RAK: "מרוקו",
  RBA: "מרוקו",
  CMN: "מרוקו",
  VIE: "אוסטריה",
  LGW: "בריטניה",
  LHR: "בריטניה",
  STN: "בריטניה",
  LTN: "בריטניה",
  BER: "גרמניה",
  MUC: "גרמניה",
  FRA: "גרמניה",
  AMS: "הולנד",
  BRU: "בלגיה",
  ZRH: "שווייץ",
  GVA: "שווייץ",
  CDG: "צרפת",
  ORY: "צרפת",
  NCE: "צרפת",
  LIS: "פורטוגל",
  FAO: "פורטוגל",
  TBS: "גאורגיה",
  BUS: "גאורגיה",
  EVN: "ארמניה",
  GYD: "אזרבייג׳ן",
  BEG: "סרביה",
  TIA: "אלבניה",
  SKP: "מקדוניה",
  ZAG: "קרואטיה",
  DBV: "קרואטיה",
  SPU: "קרואטיה",
  RIX: "לטביה",
  TLL: "אסטוניה",
  CAI: "מצרים",
  AMM: "ירדן",
  DOH: "קטאר",
  BAH: "בחריין",
  BKK: "תאילנד",
  DMK: "תאילנד",
  HKT: "תאילנד",
  SIN: "סינגפור",
  NRT: "יפן",
  HND: "יפן",
  ICN: "קוריאה הדרומית",
  JFK: "ארה״ב",
  EWR: "ארה״ב",
  LAX: "ארה״ב",
  MIA: "ארה״ב",
  YYZ: "קנדה",
  BOM: "הודו",
  DEL: "הודו",
  MLE: "מאלדיבים",
  CMB: "סרי לנקה",
  ETH: "ישראל",
  ETM: "ישראל",
};
