#!/usr/bin/env node
/**
 * One-time setup — generates secrets and writes .env.local at repo root.
 */

import { randomBytes } from "node:crypto";
import { readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "../..");
const ENV_PATH = path.join(ROOT, ".env.local");

function secret(bytes = 32) {
  return randomBytes(bytes).toString("hex");
}

async function fileExists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

function parseEnv(text) {
  const map = new Map();
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx === -1) continue;
    map.set(trimmed.slice(0, idx), trimmed.slice(idx + 1));
  }
  return map;
}

async function main() {
  const existing = (await fileExists(ENV_PATH))
    ? parseEnv(await readFile(ENV_PATH, "utf8"))
    : new Map();

  const merged = new Map(existing);

  if (!merged.get("CRON_SECRET")) merged.set("CRON_SECRET", secret());
  if (!merged.get("FEED_API_SECRET")) merged.set("FEED_API_SECRET", secret());
  merged.set("FLIGHT_DEALS_MAX_PRICE_USD", merged.get("FLIGHT_DEALS_MAX_PRICE_USD") || "50");

  const lines = [
    "# Auto-generated by flight-deals setup",
    `CRON_SECRET=${merged.get("CRON_SECRET")}`,
    `FEED_API_SECRET=${merged.get("FEED_API_SECRET")}`,
    `FLIGHT_DEALS_MAX_PRICE_USD=${merged.get("FLIGHT_DEALS_MAX_PRICE_USD")}`,
    "",
    "# === בחר מקור מחירים אחד (מהכי קל) ===",
    "",
    "# 1. Travelpayouts (מומלץ — travelpayouts.com → Developers → API Token)",
    `TRAVELPAYOUTS_TOKEN=${merged.get("TRAVELPAYOUTS_TOKEN") || ""}`,
    "",
    "# 2. SerpAPI (serpapi.com — הרשמה עם Google)",
    `SERPAPI_API_KEY=${merged.get("SERPAPI_API_KEY") || ""}`,
    "",
    "# 3. Amadeus",
    `AMADEUS_CLIENT_ID=${merged.get("AMADEUS_CLIENT_ID") || ""}`,
    `AMADEUS_CLIENT_SECRET=${merged.get("AMADEUS_CLIENT_SECRET") || ""}`,
    "",
    "# 4. בדיקה בלי הרשמה",
    `FLIGHT_DEALS_DEMO=${merged.get("FLIGHT_DEALS_DEMO") || ""}`,
    "",
    "# WhatsApp — שם הקבוצה (הבוט ימצא אוטומטית)",
    `WHATSAPP_GROUP_NAME=${merged.get("WHATSAPP_GROUP_NAME") || ""}`,
    `WHATSAPP_GROUP_CHAT_ID=${merged.get("WHATSAPP_GROUP_CHAT_ID") || ""}`,
    "",
    "# Green API (אופציונלי ל-Vercel)",
    `GREEN_API_INSTANCE=${merged.get("GREEN_API_INSTANCE") || ""}`,
    `GREEN_API_TOKEN=${merged.get("GREEN_API_TOKEN") || ""}`,
    "",
    `KV_REST_API_URL=${merged.get("KV_REST_API_URL") || ""}`,
    `KV_REST_API_TOKEN=${merged.get("KV_REST_API_TOKEN") || ""}`,
    "",
  ];

  await writeFile(ENV_PATH, lines.join("\n"), "utf8");

  console.log("✅ נוצר/עודכן:", ENV_PATH);
  console.log("");
  console.log("🔑 מקור מחירים — בחר אחד:");
  console.log("   1. Travelpayouts (הכי קל): https://www.travelpayouts.com/developers/api");
  console.log("   2. SerpAPI (עם Google):    https://serpapi.com/users/sign_up");
  console.log("   3. בדיקה בלי הרשמה:       FLIGHT_DEALS_DEMO=true");
  console.log("");
  console.log("אחרי זה: npm run flight-deals:start");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
