#!/usr/bin/env node
/**
 * One-time setup — generates secrets and writes .env.local at repo root.
 * Run: node scripts/flight-deals-whatsapp/setup.mjs
 */

import { randomBytes } from "node:crypto";
import { readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "../..");
const ENV_PATH = path.join(ROOT, ".env.local");
const EXAMPLE_PATH = path.join(ROOT, ".env.example");

function secret(bytes = 32) {
  return randomBytes(bytes).toString("hex");
}

async function fileExists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

function parseEnv(text) {
  const map = new Map();
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx === -1) continue;
    map.set(trimmed.slice(0, idx), trimmed.slice(idx + 1));
  }
  return map;
}

function serializeEnv(map, comments) {
  const lines = [];
  for (const block of comments) {
    if (block.header) lines.push(block.header);
    for (const key of block.keys) {
      const value = map.get(key) ?? "";
      lines.push(`${key}=${value}`);
    }
    lines.push("");
  }
  return lines.join("\n").trimEnd() + "\n";
}

async function main() {
  const example = await readFile(EXAMPLE_PATH, "utf8");
  const existing = (await fileExists(ENV_PATH))
    ? parseEnv(await readFile(ENV_PATH, "utf8"))
    : new Map();
  const fresh = parseEnv(example);

  const merged = new Map(fresh);

  for (const [key, value] of existing) {
    if (value) merged.set(key, value);
  }

  if (!merged.get("CRON_SECRET") || merged.get("CRON_SECRET").includes("generate")) {
    merged.set("CRON_SECRET", secret());
  }
  if (!merged.get("FEED_API_SECRET") || merged.get("FEED_API_SECRET").includes("generate")) {
    merged.set("FEED_API_SECRET", secret());
  }

  merged.set("FLIGHT_DEALS_MAX_PRICE_USD", merged.get("FLIGHT_DEALS_MAX_PRICE_USD") || "50");
  merged.set("FLIGHT_DEALS_ORIGIN", "TLV");

  const output = serializeEnv(merged, [
    {
      header: "# Auto-generated by scripts/flight-deals-whatsapp/setup.mjs",
      keys: ["FEED_API_SECRET", "CRON_SECRET"],
    },
    {
      header: "# Amadeus — https://developers.amadeus.com/ (חינם, 2 דקות)",
      keys: ["AMADEUS_CLIENT_ID", "AMADEUS_CLIENT_SECRET", "AMADEUS_API_BASE"],
    },
    {
      header: "# בוט טיסות",
      keys: ["FLIGHT_DEALS_MAX_PRICE_USD", "FLIGHT_DEALS_ORIGIN"],
    },
    {
      header: "# WhatsApp — שם הקבוצה (הבוט ימצא אותה אוטומטית)",
      keys: ["WHATSAPP_GROUP_NAME", "WHATSAPP_GROUP_CHAT_ID"],
    },
    {
      header: "# Green API (אופציונלי — לפרודקשן ב-Vercel)",
      keys: ["GREEN_API_INSTANCE", "GREEN_API_TOKEN"],
    },
    {
      header: "# Telegram (אופציונלי)",
      keys: ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID"],
    },
    {
      header: "# Redis / אתר",
      keys: ["KV_REST_API_URL", "KV_REST_API_TOKEN", "NEXT_PUBLIC_SITE_URL"],
    },
  ]);

  await writeFile(ENV_PATH, output, "utf8");

  console.log("✅ נוצר/עודכן:", ENV_PATH);
  console.log("");
  console.log("השלבים שנשארו לך:");
  console.log("  1. הדבק AMADEUS_CLIENT_ID + AMADEUS_CLIENT_SECRET ב-.env.local");
  console.log("  2. הרץ: npm run flight-deals:start");
  console.log("  3. סרוק QR ב-WhatsApp → מכשירים מקושרים");
  console.log("  4. כשאגיד — פתח קבוצה ותגיד לי את השם");
  console.log("");
  console.log("CRON_SECRET ו-FEED_API_SECRET נוצרו אוטומטית.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
